### PR TITLE
Fixed unhandled IOException when cleaning mods

### LINKED ISSUE #138: Exception when cleaning mods where some file are inaccessible
Add check for IOException and UnauthorizedAccessException exceptions and report error to user.

Sentry Issue: [XCOM2-LAUNCHER-1N](https://sentry.io/organizations/x2communitycore/issues/1233446130/?referrer=github_integration)

### PR DESCRIPTION
**Pull request by RevZero**
The user will now be informed if something goes wrong and has the option to continue the processing or to abort. Resolves #138.

### CODE REVIEW

File: xcom2-launcher/xcom2-launcher/Forms/CleanModsForm.cs [hunk 1]
```diff
@@ -24,35 +24,47 @@ public CleanModsForm(Settings settings)
...
-                    if (source_mode == "src_all_radiobutton")
-                        deleteSourceFiles(m);
+                    // Source Files
+                    if (hasSourceFiles(m) && !hasCookedPCConsole(m))
+                    {
+                        if (source_mode == "src_all_radiobutton")
+                            deleteSourceFiles(m);
+
+                        else if (source_mode == "src_xcomgame_radiobutton")
+                            if (hasXComGameSourceFiles(m))
```
Comment (Xymanek) [inline xcom2-launcher/xcom2-launcher/Forms/CleanModsForm.cs]: Oh god. Braces please

Comment (RevZero) [reply xcom2-launcher/xcom2-launcher/Forms/CleanModsForm.cs]: You mean the fact that the original author left out braces for the one liners? I do not like that as well, but preferred not to touch anything that wasn't needed. 
I have no clue what the cleaning stuff is supposed to do in detail and the code from the CleanModsForm is horrible to look at in general. The option to select another shader cache cleaning method is never made available.

Please create a new ticket if we want to touch the "cleaning" implementation for a future release.
