### PR TITLE
Mod Update fixes

### LINKED ISSUE #9: Manually installed mod not working
Hi,

The Fallout Ranger Pack was recently accidentally removed from Steam, but thankfully there are still downloads available from other sources.  Unfortunately, these don't seem to be compatible with the AML.  I have a Mods folder inside XComGame, and when I launch with the normal steam mod selector, the mod appears and the items appear in the character creator in game.  However, when I use the AML, the mod isn't even being installed - the size is listed as 0, along with the create and update fields being the unix start time version of 0 (Jan 1 1970).  The state is "Not Loaded" and right clicking and selecting "Show in explorer" brings up my home documents directory rather than the actual mod folder. Anything I can do to fix it?

ranger pack issue

### PR DESCRIPTION
**Pull request by RevZero**
fix - Mods were updated with uninitialized/invalid data if the Workshop request failed. Resolves #9.
chg - Only update the mod author name during a mod update, when the steam username request was actually successful, instead of changing it back to default value "unknown".
chg - Some minor re-factoring.

### CODE REVIEW

**Comment by Xymanek** [comment]
Could fix the indentation to be consistent? Looks like the old code used spaces and you are using tabs.

It's really hard to read the diff right now...

**Comment by RevZero** [comment]
@Xymanek: Oh, I didn't notice because my local diff-viewer was set to ignore white-space changes. I changed tab indents to spaces for code-style consistency.

PS: You can choose to "Hide whitespace changes" in the Github Diff-viewer in case you did not know.

File: xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs [hunk 1]
```diff
@@ -205,66 +206,66 @@ internal void UpdateMod(ModEntry m, Settings settings)
...
             // Check Workshop for infos
             if (m.WorkshopID != 0)
             {
-                var publishedID = (ulong) m.WorkshopID;
-
-                var value = Workshop.GetDetails(publishedID, string.IsNullOrEmpty(m.Description));
+                workshopDetails = Workshop.GetDetails((ulong) m.WorkshopID, string.IsNullOrEmpty(m.Description));
+            }
 
+            if (workshopDetails.m_eResult == EResult.k_EResultOK)
```
Comment (Xymanek) [inline xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: You sure this condition will evaluate to false for failed requests and local mods?

File: xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs [hunk 2]
```diff
@@ -279,13 +280,12 @@ internal void UpdateMod(ModEntry m, Settings settings)
...
-                    m.SetRequiresWOTC(modinfo.RequiresXPACK);
-
+                    var modInfo = new ModInfo(m.GetModInfoFile());
+                    m.SetRequiresWOTC(modInfo.RequiresXPACK);
                 }
-                catch (InvalidOperationException)
+                catch (InvalidOperationException ex)
                 {
-                    return;
+                    Debug.WriteLine(ex.Message);
```
Comment (Xymanek) [inline xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: What will this do on "live" builds?

File: xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs (hunk 1 above)
Comment (RevZero) [reply xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: Yes, m_eResult is initialized to 0 (which is actually a non-existent EResult value) when SteamUGCDetails_t is created.

File: xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs (hunk 2 above)
Comment (RevZero) [reply xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: Debug calls are removed on a Release build (DEBUG not defined). A debug message is better that just ignoring the result when debugging. The "return" was redundant because the execution path in that function is finished at that point.

File: xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs (hunk 1 above)
Comment (Xymanek) [reply xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: > which is actually a non-existent EResult value

Right, this is the part that got me confused. I thought it would initialize to the first enum value (which is `k_EResultOK`)

File: xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs (hunk 2 above)
Comment (Xymanek) [reply xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: I see your logic. Maybe it's better to throw an exception inside `#if DEBUG`? Messages in "output" window can be easily missed

Comment (RevZero) [reply xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: An InvalidOperationException maybe expected at that point. It is generally acceptable to swallow specific exception that are expected to happen but can't be or aren't required to be handled. However, it is always good to leave a code comment in that case. Now we don't what exactly the original author intended, but I think we can leave it this way. I already thought about implementing a "Logger" for cases like this. Its really nice to have a log file to be able to follow program flow in case of issues.
