### PR TITLE
Handle potential ArgumentException when processing mod directories

### LINKED ISSUE #126: Improve error handling when detecting mod directories
Improve XCOM2.DetectModDirs() error handling. Specifically catching and logging System.ArgumentException for each individual directory.

### PR DESCRIPTION
**Pull request by RevZero**
See commit log. Resolves #126.

### CODE REVIEW

File: xcom2-launcher/xcom2-launcher/Classes/XCOM/XCOM2.cs [hunk 1]
```diff
@@ -125,22 +128,43 @@ internal static void ImportActiveMods(Settings settings, bool wotc)
...
+                    if (Path.IsPathRooted(modDir))
+                    {
+                        // make sure all directories end with '\' (can only happen if someone adds a dir manually?)
+                        dir = modDir.EndsWith(@"\") ? modDir : modDir + @"\";
+                    }
+                    else
+                    {
+                        // No idea if or why this is required and if it is even correct, so lets log potential uses to Sentry.
+                        SentrySdk.CaptureMessage($"Non rooted mod directory '{modDir}'", SentryLevel.Debug);
+                        dir = Path.GetFullPath(Path.Combine(GameDir, "bin", "Win64", modDir));
```
Comment (Xymanek) [inline xcom2-launcher/xcom2-launcher/Classes/XCOM/XCOM2.cs]: Here is from my vanilla `DefaultEngine.ini`:
```ini
[Engine.DownloadableContentEnumerator]
+ModRootDirs=../../XcomGame/Mods/
```
And since everything works fine I'm not sure if non-rooted paths are an issue. That said, I never launch vanilla
