### PR TITLE
Changed mod ID comparison to ignore case

### LINKED ISSUE #94: Mod ID comparison is case sensitive
Hello.
Recently I have a little problem, which turned is a problem with 2 mods having same mod ID, but one had ID "M96MATTOCK" and second "M96Mattock".
For Mod Launcher (newest version), it was not duplicate, as it wasn't showing any "duplicate id error", but for game it was - one other mod was trying to do something with this, game instead would crash at the start.

Is there any option to prevent this kind of situation in future?

### PR DESCRIPTION
**Pull request by RevZero**
Mod ID comparison is now case insensitive. Resolves #94.
See commit message for details.

### CODE REVIEW

File: xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs [hunk 1]
```diff
@@ -83,26 +82,34 @@ private void UpdateModsConflictState(IEnumerable<ModConflict> activeConflicts)
             }
         }
 
-        public void ImportMods(string dir)
+        public void ImportMods(List<string> modPaths)
         {
-            if (!Directory.Exists(dir))
+            if (modPaths == null)
                 return;
```
Comment (Xymanek) [inline xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: This check makes more sense to throw `ArgumentNullException`

File: xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs [hunk 2]
```diff
@@ -83,26 +82,34 @@ private void UpdateModsConflictState(IEnumerable<ModConflict> activeConflicts)
...
 
-            // (try to) load mods
-            foreach (var modDir in Directory.GetDirectories(dir))
+            foreach (var dir in modPaths)
             {
-                var source = modDir.IndexOf(@"\SteamApps\workshop\", StringComparison.OrdinalIgnoreCase) != -1
-                    ? ModSource.SteamWorkshop
-                    : ModSource.Manual;
+                if (!Directory.Exists(dir))
+                    return;
```
Comment (Xymanek) [inline xcom2-launcher/xcom2-launcher/Classes/Mod/ModList.cs]: You probably meant `continue`?
