### PR TITLE
Prevent unhandled exception when closing SettingsDialog with invalid base path

### LINKED ISSUE #149: Exception when an invalid base path is specified in Settings
AML currently crashes, when the specified base path contains invalid characters or is empty.

### PR DESCRIPTION
**Pull request by RevZero**
Resolves #149.

### CODE REVIEW

File: xcom2-launcher/xcom2-launcher/Forms/SettingsDialog.cs [hunk 1]
```diff
@@ -117,8 +117,14 @@ private void bOK_Click(object sender, EventArgs e)
...
 
+            // Verify settings
+            if (!Directory.Exists(gamePathTextBox.Text)) {
+                MessageBox.Show("The specified base path does not exist.", "Warning", MessageBoxButtons.OK, MessageBoxIcon.Warning);
+                return;
+            }
+            
             // Apply changes
-            Settings.GamePath = Path.GetFullPath(gamePathTextBox.Text);
+            Settings.GamePath = gamePathTextBox.Text;
```
Comment (Xymanek) [inline xcom2-launcher/xcom2-launcher/Forms/SettingsDialog.cs]: Do we not need `Path.GetFullPath`?

Comment (RevZero) [reply xcom2-launcher/xcom2-launcher/Forms/SettingsDialog.cs]: I do not see how this would make sense. Even IF a user would specify an incomplete path, GetFullPath() uses the "current directory" to create a fully qualified path. This normally isn't the game directory. So no, I think it is not required. At least I do not see a valid use case.

Comment (RevZero) [reply xcom2-launcher/xcom2-launcher/Forms/SettingsDialog.cs]: Oh and we are catching incomplete paths with Directory.Exists() anyway.

Comment (Xymanek) [reply xcom2-launcher/xcom2-launcher/Forms/SettingsDialog.cs]: From `Directory.Exists()` docs:

> The path parameter is permitted to specify relative or absolute path information. Relative path information is interpreted as relative to the current working directory.

So it will accept relative paths.. I think we should keep `Path.GetFullPath()` just to be sure

Comment (RevZero) [reply xcom2-launcher/xcom2-launcher/Forms/SettingsDialog.cs]: Valid point. As Directory.Exists() already "catches" invalid characters or an empty path, leaving GetFullPath() in should be fine.
